name: Build & Publish

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build & Publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install packages
              run: npm install
            - name: Build
              run: npm run build
            - name: Upload Release Asset
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: dist/safetensors.*.js
                tag: ${{ github.ref }}
                file_glob: true